# Generated by Django 2.1.4 on 2018-12-18 21:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='APIHandler',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mock_type', models.CharField(choices=[('http', 'http'), ('ws', 'ws')], default='http', max_length=10)),
                ('request_path', models.CharField(max_length=3000)),
                ('request_method', models.CharField(choices=[('GET', 'GET'), ('POST', 'POST'), ('PUT', 'PUT'), ('DELETE', 'DELETE'), ('HEAD', 'HEAD'), ('CONNECT', 'CONNECT'), ('OPTIONS', 'OPTIONS'), ('TRACE', 'TRACE'), ('PATCH', 'PATCH')], default='GET', max_length=10)),
                ('request_body', models.TextField(blank=True, null=True)),
                ('response_body', models.TextField(blank=True, null=True)),
                ('response_content_type', models.CharField(choices=[('text/plain', 'Plain (text/plain)'), ('text/html', 'HTML (text/html)'), ('application/json', 'JSON (application/json)'), ('application/javascript', 'JSONP (application/javascript)')], default='text/plain', max_length=30)),
                ('response_status_code', models.PositiveSmallIntegerField(choices=[(None, '-- Information responses --'), (100, '100 - Continue'), (101, '101 - Switching Protocol'), (102, '102 - Processing (WebDAV)'), (103, '103 - Early Hints'), (None, '-- Successful responses --'), (200, '200 - OK'), (201, '201 - Created'), (202, '202 - Accepted'), (203, '203 - Non-Authoritative Information'), (204, '204 - No Content'), (205, '205 - Reset Content'), (206, '206 - Partial Content'), (207, '207 - Multi-Status (WebDAV)'), (208, '208 - Multi-Status (WebDAV)'), (226, '226 - IM Used'), (None, '-- Redirection messages --'), (300, '300 - Multiple Choice'), (301, '301 - Moved Permanently'), (302, '302 - Found'), (303, '303 - See Other'), (304, '304 - Not Modified'), (305, '305 - Use Proxy'), (306, '306 - Unused'), (307, '307 - Temporary Redirect'), (308, '308 - Permanent Redirect'), (None, '-- Client error responses --'), (400, '400 - Bad Request'), (401, '401 - Unauthorized'), (402, '402 - Payment Required'), (403, '403 - Forbidden'), (404, '404 - Not Found'), (405, '405 - Method Not Allowed'), (406, '406 - Not Acceptable'), (407, '407 - Proxy Authentication Required'), (408, '408 - Request Timeout'), (409, '409 - Conflict'), (410, '410 - Gone'), (411, '411 - Length Required'), (412, '412 - Precondition Failed'), (413, '413 - Payload Too Large'), (414, '414 - URI Too Long'), (415, '415 - Unsupported Media Type'), (416, '416 - Requested Range Not Satisfiable'), (417, '417 - Expectation Failed'), (418, "418 - I'm a teapot"), (421, '421 - Misdirected Request'), (422, '422 - Unprocessable Entity (WebDAV)'), (423, '423 - Locked (WebDAV)'), (424, '424 - Failed Dependency (WebDAV)'), (425, '425 - Too Early'), (426, '426 - Upgrade Required'), (428, '428 - Precondition Required'), (429, '429 - Too Many Requests'), (431, '431 - Request Header Fields Too Large'), (451, '451 - Unavailable For Legal Reasons'), (None, '-- Server error responses --'), (500, '500 - Internal Server Error'), (501, '501 - Not Implemented'), (502, '502 - Bad Gateway'), (503, '503 - Service Unavailable'), (504, '504 - Gateway Timeout'), (505, '505 - HTTP Version Not Supported'), (506, '506 - Variant Also Negotiates'), (507, '507 - Insufficient Storage'), (508, '508 - Loop Detected (WebDAV)'), (510, '510 - Not Extended'), (511, '511 - Network Authentication Required')], default=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='APIRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('request_path', models.CharField(max_length=3000)),
                ('request_method', models.CharField(choices=[('GET', 'GET'), ('POST', 'POST'), ('PUT', 'PUT'), ('DELETE', 'DELETE'), ('HEAD', 'HEAD'), ('CONNECT', 'CONNECT'), ('OPTIONS', 'OPTIONS'), ('TRACE', 'TRACE'), ('PATCH', 'PATCH')], default='GET', max_length=10)),
                ('request_body', models.TextField(blank=True, null=True)),
                ('request_headers', models.TextField(blank=True, null=True)),
                ('response_body', models.TextField(blank=True, null=True)),
                ('response_content_type', models.CharField(choices=[('text/plain', 'Plain (text/plain)'), ('text/html', 'HTML (text/html)'), ('application/json', 'JSON (application/json)'), ('application/javascript', 'JSONP (application/javascript)')], default='text/plain', max_length=30)),
                ('response_status_code', models.PositiveSmallIntegerField(choices=[(None, '-- Information responses --'), (100, '100 - Continue'), (101, '101 - Switching Protocol'), (102, '102 - Processing (WebDAV)'), (103, '103 - Early Hints'), (None, '-- Successful responses --'), (200, '200 - OK'), (201, '201 - Created'), (202, '202 - Accepted'), (203, '203 - Non-Authoritative Information'), (204, '204 - No Content'), (205, '205 - Reset Content'), (206, '206 - Partial Content'), (207, '207 - Multi-Status (WebDAV)'), (208, '208 - Multi-Status (WebDAV)'), (226, '226 - IM Used'), (None, '-- Redirection messages --'), (300, '300 - Multiple Choice'), (301, '301 - Moved Permanently'), (302, '302 - Found'), (303, '303 - See Other'), (304, '304 - Not Modified'), (305, '305 - Use Proxy'), (306, '306 - Unused'), (307, '307 - Temporary Redirect'), (308, '308 - Permanent Redirect'), (None, '-- Client error responses --'), (400, '400 - Bad Request'), (401, '401 - Unauthorized'), (402, '402 - Payment Required'), (403, '403 - Forbidden'), (404, '404 - Not Found'), (405, '405 - Method Not Allowed'), (406, '406 - Not Acceptable'), (407, '407 - Proxy Authentication Required'), (408, '408 - Request Timeout'), (409, '409 - Conflict'), (410, '410 - Gone'), (411, '411 - Length Required'), (412, '412 - Precondition Failed'), (413, '413 - Payload Too Large'), (414, '414 - URI Too Long'), (415, '415 - Unsupported Media Type'), (416, '416 - Requested Range Not Satisfiable'), (417, '417 - Expectation Failed'), (418, "418 - I'm a teapot"), (421, '421 - Misdirected Request'), (422, '422 - Unprocessable Entity (WebDAV)'), (423, '423 - Locked (WebDAV)'), (424, '424 - Failed Dependency (WebDAV)'), (425, '425 - Too Early'), (426, '426 - Upgrade Required'), (428, '428 - Precondition Required'), (429, '429 - Too Many Requests'), (431, '431 - Request Header Fields Too Large'), (451, '451 - Unavailable For Legal Reasons'), (None, '-- Server error responses --'), (500, '500 - Internal Server Error'), (501, '501 - Not Implemented'), (502, '502 - Bad Gateway'), (503, '503 - Service Unavailable'), (504, '504 - Gateway Timeout'), (505, '505 - HTTP Version Not Supported'), (506, '506 - Variant Also Negotiates'), (507, '507 - Insufficient Storage'), (508, '508 - Loop Detected (WebDAV)'), (510, '510 - Not Extended'), (511, '511 - Network Authentication Required')], default=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_fake_api.APIHandler')),
            ],
            options={
                'ordering': ('-pk',),
            },
        ),
    ]
