# Generated by Django 2.1.4 on 2018-12-19 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_fake_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apirequest',
            old_name='request',
            new_name='api_handler',
        ),
    ]
